version: '1.0'

services:
  messenger:
    image: kautilyak/messenger:1.0
    container-name: messenger
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: endpoint_db
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    ports:
      - "8081:8080"
    depends_on:
      - mongo
      - rabbitmq
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    logging:
      driver: none

  rabbitmq:
    image: rabbitmq
    logging:
      driver: none
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest